- name: Custom CPU model configuration file
  ansible.builtin.template:
    src: "{{ item | basename }}.jinja2"
    dest: "{{ item }}"
    # due to pve file system no setting of owner,group,mode allowed
    # mode: '0644'
  loop:
    - "/etc/pve/virtual-guest/cpu-models.conf"
  tags:
    - skip_ansible_lint
