- name: Set fact
  ansible.builtin.set_fact:
    ntp_include_name: "{{ 'systemd-timesyncd' if ntp_solution == 'systemd_timesyncd' else 'chrony' }}"

- name:  Include the preferred solution
  include_tasks: "ntp-{{ ntp_include_name }}.yml"
