- name: Apt update
  ansible.builtin.apt:
   cache_valid_time: 3600

- name: Install packages
  ansible.builtin.apt:
   name: "{{ packages }}"
  vars:
   packages:
    - ethtool
    - vim
    - net-tools
    - sysfsutils
    # just auto-install packages
    - unattended-upgrades
    - apt-listchanges
    - systemd-timesyncd
#  when: proxmox_host_network_quirk == True
