- name: Create files
  ansible.builtin.template:
    src: "{{ item | basename }}.jinja2"
    dest: "{{ item }}"
    owner: root
    group: root
    mode: '0644'
  loop:
    - "/etc/sysctl.d/vmdirty.conf"
# - name:     update sysctl
#   command:  "sysctl"
#   when:     proxmox_grub_files.changed
