- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop:
    - /etc/fedora-cloud-sync

- name: Create config file if does not exist
  ansible.builtin.template:
    src: "{{ item | basename }}.jinja2"
    dest: "{{ item }}"
    owner: root
    group: root
    mode: '0644'
    # force: no      # if the file exists we do nothing
  loop:
    - "/etc/fedora-cloud-sync/fedora-cloud-sync.conf"
